### PR TITLE
Added links

### PR DESCRIPTION
**Pull request by bthirion**
Added links to crowdcast and Youtube broadcast for first day.

### CODE REVIEW

**Comment by bthirion** [comment]
Silly question: How do I build the page to check that everything is OK ?

**Comment by kchawla-pi** [comment]
It should build automatically within a few minutes after pushing a commit.
You just have to refresh the page in the browser.

**Comment by bthirion** [comment]
Sure, but after merge, right ? Any approval ?

**Comment by emdupre** [comment]
I'm approving now :) Huge thanks, @bthirion !

**Comment by GaelVaroquaux** [comment]
Thanks, @bthirion !!

**Pull request merged**
